name: Compile and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # Make sure the @v0.9.0 matches the current version of the action
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Backup current version
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
          cp -r /var/www/html/testcompang ~/testcompang-$(date +%F-%T) 2>/dev/null || :
        EOF

    - name: Build the project
      run: |
        npm install
        ls -l
        npx ng build --configuration=production

    - name: Deploy to server
      run: |
        rsync -avz --delete-after ./dist/ ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:/var/www/html/
