name: Compile and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH agent
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Backup current version
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
          cp -r /var/www/html/testcompang ~/testcompang-$(date +%F-%T)
        EOF

    - name: Deploy new version
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
          mkdir -p ~/testcompang
          cd ~/testcompang
          git init
          git remote add origin https://github.com/IchirokuXVI/testcompang.git
          git pull origin main
          npm install
          ng build --configuration=production
          rm -r /var/www/html/testcompang
          mv /dist/* /var/www/html/testcompang
        EOF
