name: Deploy with Rollback

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Backup current version
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
          cp -r /var/www/html/testcompang ~/testcompang-$(date +%F-%T)
        EOF

    - name: Deploy new version
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd ~/testcompang
          git pull origin main
          npm install
          ng build --configuration=production
          rm -r /var/www/html/testcompang
          mv /dist/* /var/www/html/testcompang
        EOF
